server:
  port: 8080
  servlet:
    context-path: /

spring:

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/toyshop?serverTimezone=Asia/Seoul
    username: toyshop
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  security:    oauth2:      client:        registration:          google: #/oauth2/authorization/google
            client-id: 
            client-secret: 
            scope:            - email
            - profile
  
wc:
  key: wc1234
    
file:
  path: C:/Users/kk/Desktop/Spring-instagram/toyshop/src/main/resources/static/img/